### ISSUE TITLE
Freezing effect not showing in holosphere/workbench

### ISSUE THREAD

**Issue by iron431** [RedPxnda/tetrutils#1]
I made a custom material for tinker's construct's cobalt with the freezing effect - and it works - but no tooltip displays in the holosphere or when selecting the material in the workbench like the other effects (piercing, bleeding, etc) do.
![image](https://user-images.githubusercontent.com/34083081/208255459-761ca318-ab65-4f58-bbfe-31a9ff88d148.png)
![image](https://user-images.githubusercontent.com/34083081/208255500-6779daa4-75b0-48a5-980f-1f063b8f83e5.png)
As you can see, there is no freezing tooltip even though the effect is applied and works in game.

**Comment by RedPxnda** [comment]
Hello! Yes, I am aware of this. This is in fact fixed in a dev version that I've had for months and just haven't bothered releasing, because of motivation issues. If you want me to push this update, I can.

**Comment by iron431** [comment]
That would be great if you could! Sorry to hear about your motivation issues, this mod have a very interesting prospect and seems to be the only project with the ambition to add some really cool mechanics to tetra.

**Comment by RedPxnda** [comment]
Okay! I'll publish that to CF rn, so keep your eyes out for that.
I'll just tell you now, so that you're aware: this update adds quite a few other things:

- Revamped freeze effect; now it stacks(depending on effect efficiency) and has particles
- Adds holosphere and workbench displays for effects
- Adds two module conditions: Player wearing some kind of curio, and an achievement requirement
- Frenzy effect: consecutive hits increases damage
- Wisdom effect: increases xp gain from killing creatures

**Comment by iron431** [comment]
nice, thank you!
